### ISSUE TITLE
Installation stuck

### ISSUE THREAD

**Issue by cphyc** [hadim/jupyterlab_gist#7] opened 2018-05-14 08:05 UTC
Hi,
When trying to install this package, jupyterlab gets stuck at installation at the step [1/4] where it's resolving packages. I tried installing it directly using
```
jupyter labextension install @hadim/jupyterlab_gist
```
as well as 
```
yarn install
yarn build
jupyter labextension link .
```

Here is the log
```
jupyter labextension install @hadim/jupyterlab_gist  
> /usr/bin/npm pack @hadim/jupyterlab_gist
npm notice 
npm notice 📦  @hadim/jupyterlab_gist@0.3.1
npm notice === Tarball Contents === 
npm notice 0     package                        
npm notice 1.1kB LICENSE                        
npm notice 803B  README.md                      
npm notice 0     lib                            
npm notice 1.0kB package.json                   
npm notice 0     style                          
npm notice 716B  lib/index.d.ts                 
npm notice 5.0kB lib/index.js                   
npm notice 0     style/icons                    
npm notice 451B  style/index.css                
npm notice 2.8kB style/icons/copyURLGistIcon.svg
npm notice 3.2kB style/icons/deleteGistIcon.svg 
npm notice 2.5kB style/icons/postGistIcon.svg   
npm notice === Tarball Details === 
npm notice name:          @hadim/jupyterlab_gist                  
npm notice version:       0.3.2                                   
npm notice filename:      hadim-jupyterlab_gist-0.3.1.tgz         
npm notice package size:  5.4 kB                                  
npm notice unpacked size: 17.6 kB                                 
npm notice shasum:        e46b99fe6aac36d3b596f428419dac31d18b01cd
npm notice integrity:     sha512-jVp+qMnxTd+9Q[...]jNJ0S3ttLSnFA==
npm notice total files:   13                                      
npm notice 
hadim-jupyterlab_gist-0.3.1.tgz
> node /PATH/TO/MY/VIRTUALENV/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.5.1
(node:30373) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info No lockfile found.
[1/4] Resolving packages...
⠐ @hadim/jupyterlab_gist@file:../extensions/hadim-jupyterlab_gist-0.3.1.tgz
```
The last line will stay forever (I waited 24hrs then killed it).

**Comment by cphyc** [comment] 2018-05-14 08:38
After some research, it seems to be a `yarn`+`node`v10 issue. See https://github.com/jupyter-widgets/ipywidgets/issues/2061, which is fixed by PR https://github.com/yarnpkg/yarn/pull/5769

**Comment by nunocalaim** [comment] 2018-05-15 11:11
Does anyone know of a workaround to this before all the PR are merged and accepted at the different projects?

**Comment by hadim** [comment] 2018-07-16 17:03
Installation works for me (maybe try to update yarn to 1.7.0 or 1.8.0). Please reopen if the issue is still here.

**Closed as completed by hadim** 2018-07-16 17:03 UTC

**Comment by hadim** [comment] 2018-07-16 17:17
The issue is because JLab currently ships with yarn 1.5.1 that does not work well with Node. The issue will be released with JLab 0.33.0.

**Comment by hadim** [comment] 2018-07-16 17:23
They recently downgraded 0.33 to yarn 1.6.0 (https://github.com/jupyterlab/jupyterlab/pull/4804) because of another bug.

**Comment by hadim** [comment] 2018-07-16 21:04
`conda install --force nodejs==9.11.1` is a good and quick temporary workaround.
